
DROP TABLE IF EXISTS tPost;
DROP TABLE IF EXISTS tUser;

CREATE TABLE tUser (
  user_id UUID UNIQUE NOT NULL,
  username TEXT UNIQUE NOT NULL
);

CREATE TABLE tPost (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES tUser (user_id)
);
